### ISSUE TITLE
new static assert failure in complex.h

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#26]
processed source: https://gist.github.com/brooksdavis/2f7a1e70c528c9f6b31b

git bisect says the offending commit is 1039775

```
/home/bed22/git/llvm-cheri/Build/bin/clang -integrated-as --target=cheri-unknown-freebsd  -msoft-float --sysroot=/home/bed22/obj/mips.mips64/home/bed22/git/cheribsd/tmp -mabi=sandbox  -O -pipe -G0   -I/home/bed22/git/cheribsd/lib/msun/src -I/home/bed22/git/cheribsd/lib/msun/../libc/include  -I/home/bed22/git/cheribsd/lib/msun/../libc/mips  -std=gnu99 -Wsystem-headers -Werror -Wno-pointer-sign -Wno-unknown-pragmas -Wno-empty-body -Wno-string-plus-int -Wno-unused-const-variable -Wno-tautological-compare -Wno-unused-value -Wno-parentheses-equality -Wno-unused-function -Wno-enum-conversion -Wno-unused-local-typedef -Wno-switch -Wno-switch-enum -Wno-knr-promoted-parameter -Wno-parentheses -Qunused-arguments -c /home/bed22/git/cheribsd/lib/msun/src/s_carg.c -o s_carg.o
In file included from /home/bed22/git/cheribsd/lib/msun/src/s_carg.c:30:
/home/bed22/obj/mips.mips64/home/bed22/git/cheribsd/tmp/usr/include/complex.h:42:1: error: 
      static_assert failed "_Complex_I must be of type float _Complex"
_Static_assert(__generic(_Complex_I, float _Complex, 1, 0),
^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1
```

**Comment by davidchisnall** [comment]
Should be fixed now.
