### ISSUE TITLE
capabilityness of reference to a capability should be determined by LHS

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/clang#186]
```C
void * __capability foo;
void * bar = &foo;
```
produces:
```
$ clang -target cheri-unknown-freebsd -c -o /dev/null  foo.c                                                           
foo.c:2:8: error: converting capability type
      'void * __capability * __capability' to non-capability type 'void *'
      without an explicit cast; if this is intended use __cheri_fromcap
void * bar = &foo;
       ^
             (__cheri_fromcap void *)
1 error generated.
```

**Comment by brooksdavis** [comment]
Probably related to #182

**Comment by arichardson** [comment]
I broke this in e79ea8405f099352401535bb72fa4ebb25cbca8a but it should be fixed by c1f238963b33da6a026f352421835dea438a7abd
